# Generated by Django 3.2.12 on 2023-02-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fib', '0002_auto_20230221_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='port',
            field=models.CharField(max_length=9),
        ),
    ]
