# Generated by Django 3.2.12 on 2023-03-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scan_ipv_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='scan',
            name='execution',
            field=models.CharField(choices=[('SCAN', 'Scan')], default='SCAN', max_length=8),
        ),
        migrations.AlterField(
            model_name='scan',
            name='ip',
            field=models.GenericIPAddressField(default=''),
        ),
        migrations.AlterField(
            model_name='scan',
            name='port',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scanner_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], default='PENDING', max_length=8),
        ),
        migrations.AddField(
            model_name='scan',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scanner.group'),
        ),
    ]
