# Generated by Django 3.2.12 on 2023-03-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_auto_20230304_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
